### ISSUE TITLE
Before next Flight Checklist:

### ISSUE THREAD

**Issue by reuy** [reuy/Freelancer-Initiative#303]
- [ ] #296 Add new blocks to crushing wheels. 
- [ ] #302 Fix Vein Miner
- [ ] #296 Correct Stone Forge Tags
- [ ] Implement Factory Blocks Datapack
- [ ] #263 Move Iron block Chisel variants to Iron Plate
- [ ] Remove Iron Chests
- [ ] Remove Meadow
- [ ] Remove Mana and Artifice
- [ ] Remove IC2
- [ ] Remove Simply Swords
- [ ] Install Biomes Mod
- [ ] Implement all staged Skilltree Items
- [ ] Trailblazer Trait
- [ ] #287 Replace Farmers Delight Knives with Spartan Knives
- [ ] EF: Configure First Person fix patch
- [ ] #288 Drop meats and fats
- [ ] Kube JS changes
